pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [dependency-update]
      merge:
        method: squash
        strict: true