addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.9.33")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.heroku"     % "sbt-heroku"          % "2.1.4")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.4.6")
