name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: sbt cache
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ hashFiles('project/build.properties') }}
      - name: dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.m2
            ~/.cache/coursier/
          key: ${{ hashFiles('project/Dependencies.scala') }}
      - name: Trigger release in Heroku
        run: sbt release deployHeroku 
        heroku container:release -a $HEROKU_APP web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}