name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: sbt cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.sbt
          key: ${{ hashFiles('build.sbt') }}
      - name: dependencies cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.ivy2
          key: ${{ hashFiles('build.sbt') }}
      - name: login
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login
      - name: buildZookCore
        run: sbt zookcoreStub/publishLocal
      - name: build
        run: sbt docker:publish
