name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: sbt cache
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ hashFiles('project/build.properties') }}
      - name: dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.m2
            ~/.cache/coursier/
          key: ${{ hashFiles('project/Dependencies.scala') }}
      - name: create credentials
        env:
          CREDS_USERNAME: ${{ secrets.CREDS_USERNAME }}
          CREDS_PASSWORD: ${{ secrets.CREDS_PASSWORD }}
        run: echo "credentials += Credentials(\"GitHub Package Registry\",\"maven.pkg.github.com\",\"$CREDS_USERNAME\",\"$CREDS_PASSWORD\")" > credentials.sbt
      - name: Login to Heroku Container registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: build
        run: sbt docker:publish
      - name: Trigger release in Heroku
        run: heroku container:release -a $HEROKU_APP web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}