name: Integration Tests

on: push

jobs:
  it-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f /home/runner/work/zooklabs/zooklabs/src/test/resources/docker-compose.yml up -d
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: sbt cache
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ hashFiles('project/build.properties') }}
      - name: dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.m2
            ~/.cache/coursier/
          key: ${{ hashFiles('project/Dependencies.scala') }}
      - name: zookcoreStub
        run: sbt zookcoreStub / publishLocal
      - name: Test
        run: sbt it:test